-- Désactivation temporaire des contraintes pour éviter les erreurs de clé étrangère
SET FOREIGN_KEY_CHECKS = 0;

-- Création de la base de données
CREATE DATABASE IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- Table PAIEMENT
CREATE TABLE IF NOT EXISTS `PAIEMENT` (
  `numero_PAIEMENT` INT NOT NULL AUTO_INCREMENT,
  `mode_PAIEMENT` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`numero_PAIEMENT`)
) ENGINE = InnoDB;

-- Table CLIENT
CREATE TABLE IF NOT EXISTS `CLIENT` (
  `numero_CLIENT` INT NOT NULL AUTO_INCREMENT,
  `nom_CLIENT` VARCHAR(64) NOT NULL,
  `mail_CLIENT` VARCHAR(128) NOT NULL,
  `telephone_CLIENT` VARCHAR(64) NOT NULL,
  `adresse_CLIENT` VARCHAR(128) NOT NULL,
  `password_CLIENT` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`numero_CLIENT`)
) ENGINE = InnoDB;

-- Table LIVREUR
CREATE TABLE IF NOT EXISTS `LIVREUR` (
  `numero_LIVREUR` INT NOT NULL AUTO_INCREMENT,
  `nom_LIVREUR` VARCHAR(128) NOT NULL,
  `telephone_LIVREUR` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`numero_LIVREUR`)
) ENGINE = InnoDB;

-- Table COMMANDE
CREATE TABLE IF NOT EXISTS `COMMANDE` (
  `numero_COMMANDE` INT NOT NULL AUTO_INCREMENT,
  `date_COMMANDE` DATE NOT NULL,
  `statut_COMMANDE` VARCHAR(45) NOT NULL,
  `CLIENT_numero_CLIENT` INT NOT NULL,
  `LIVREUR_numero_LIVREUR` INT NOT NULL,
  PRIMARY KEY (`numero_COMMANDE`),
  INDEX `fk_COMMANDE_CLIENT_idx` (`CLIENT_numero_CLIENT`),
  INDEX `fk_COMMANDE_LIVREUR_idx` (`LIVREUR_numero_LIVREUR`),
  CONSTRAINT `fk_COMMANDE_CLIENT`
    FOREIGN KEY (`CLIENT_numero_CLIENT`)
    REFERENCES `CLIENT` (`numero_CLIENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMANDE_LIVREUR`
    FOREIGN KEY (`LIVREUR_numero_LIVREUR`)
    REFERENCES `LIVREUR` (`numero_LIVREUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table payer
CREATE TABLE IF NOT EXISTS `payer` (
  `PAIEMENT_numero_PAIEMENT` INT NOT NULL,
  `COMMANDE_numero_COMMANDE` INT NOT NULL,
  PRIMARY KEY (`PAIEMENT_numero_PAIEMENT`, `COMMANDE_numero_COMMANDE`),
  INDEX `fk_payer_PAIEMENT_idx` (`PAIEMENT_numero_PAIEMENT`),
  INDEX `fk_payer_COMMANDE_idx` (`COMMANDE_numero_COMMANDE`),
  CONSTRAINT `fk_payer_PAIEMENT`
    FOREIGN KEY (`PAIEMENT_numero_PAIEMENT`)
    REFERENCES `PAIEMENT` (`numero_PAIEMENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payer_COMMANDE`
    FOREIGN KEY (`COMMANDE_numero_COMMANDE`)
    REFERENCES `COMMANDE` (`numero_COMMANDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table PRODUIT
CREATE TABLE IF NOT EXISTS `PRODUIT` (
  `reference_PRODUIT` INT NOT NULL AUTO_INCREMENT,
  `designation_PRODUIT` VARCHAR(128) NOT NULL,
  `prix_unitaire_PRODUIT` INT NOT NULL,
  `stock_disponible_PRODUIT` INT NOT NULL,
  PRIMARY KEY (`reference_PRODUIT`)
) ENGINE = InnoDB;

-- Table LIGNE_DE_COMMANDE
CREATE TABLE IF NOT EXISTS `LIGNE_DE_COMMANDE` (
  `numero_LIGNE_DE_COMMANDE` INT NOT NULL AUTO_INCREMENT,
  `quantite_LIGNE_DE_COMMANDE` INT NOT NULL,
  `COMMANDE_numero_COMMANDE` INT NOT NULL,
  `PRODUIT_reference_PRODUIT` INT NOT NULL,
  PRIMARY KEY (`numero_LIGNE_DE_COMMANDE`),
  INDEX `fk_LIGNE_DE_COMMANDE_COMMANDE_idx` (`COMMANDE_numero_COMMANDE`),
  INDEX `fk_LIGNE_DE_COMMANDE_PRODUIT_idx` (`PRODUIT_reference_PRODUIT`),
  CONSTRAINT `fk_LIGNE_DE_COMMANDE_COMMANDE`
    FOREIGN KEY (`COMMANDE_numero_COMMANDE`)
    REFERENCES `COMMANDE` (`numero_COMMANDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIGNE_DE_COMMANDE_PRODUIT`
    FOREIGN KEY (`PRODUIT_reference_PRODUIT`)
    REFERENCES `PRODUIT` (`reference_PRODUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table RETOUR_PRODUIT
CREATE TABLE IF NOT EXISTS `RETOUR_PRODUIT` (
  `numero_RETOUR_PRODUIT` INT NOT NULL AUTO_INCREMENT,
  `motif_RETOUR_PRODUIT` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`numero_RETOUR_PRODUIT`)
) ENGINE = InnoDB;

-- Table Retourner
CREATE TABLE IF NOT EXISTS `Retourner` (
  `LIGNE_DE_COMMANDE_numero_LIGNE_DE_COMMANDE` INT NOT NULL,
  `RETOUR_PRODUIT_numero_RETOUR_PRODUIT` INT NOT NULL,
  PRIMARY KEY (`LIGNE_DE_COMMANDE_numero_LIGNE_DE_COMMANDE`, `RETOUR_PRODUIT_numero_RETOUR_PRODUIT`),
  INDEX `fk_Retourner_RETOUR_PRODUIT_idx` (`RETOUR_PRODUIT_numero_RETOUR_PRODUIT`),
  CONSTRAINT `fk_Retourner_LIGNE_DE_COMMANDE`
    FOREIGN KEY (`LIGNE_DE_COMMANDE_numero_LIGNE_DE_COMMANDE`)
    REFERENCES `LIGNE_DE_COMMANDE` (`numero_LIGNE_DE_COMMANDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Retourner_RETOUR_PRODUIT`
    FOREIGN KEY (`RETOUR_PRODUIT_numero_RETOUR_PRODUIT`)
    REFERENCES `RETOUR_PRODUIT` (`numero_RETOUR_PRODUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Réactivation des contraintes
SET FOREIGN_KEY_CHECKS = 1;
